moodle:
  url: "${MOODLE_URL}"
  token: "${MOODLE_TOKEN}" # Debe configurarse vía variable de entorno o manualmente
  target_course: "${MOODLE_TARGET_COURSE}"

qdrant:
  host: "${QDRANT_HOST}"
  port: ${QDRANT_PORT}
  collection_name: "${QDRANT_COLLECTION}"

embeddings:
  provider: "${EMBEDDING_PROVIDER}" # "ollama" o "openai"
  openai_api_key: "${OPENAI_API_KEY}" # Requerido si provider="openai"
  openai_model: "${OPENAI_EMBEDDING_MODEL}"

ollama:
  url: "${OLLAMA_URL}"
  model_name: "${OLLAMA_MODEL}"

bitnet:
  model_name: "${BITNET_MODEL}" # BitNet model for chat (not used for embeddings)

postgres:
  connection_string: "${POSTGRES_CONNECTION}"
