volumes:
  db_storage:
  n8n_storage:
  mariadb_data:
  moodle_data:
  qdrant_data:
  ollama_data:
  ollama_webui_data:

services:
  postgres:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=n8n
      - POSTGRES_NON_ROOT_USER=n8n
      - POSTGRES_NON_ROOT_PASSWORD=n8n_password
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./postgres_init.sh:/docker-entrypoint-initdb.d/postgres_init.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U postgres -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - tesis

  n8n:
    image: n8nio/n8n
    restart: always
    environment:
      # Base de datos
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
      # Autenticación
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - WEBHOOK_URL=http://localhost:5678/
      # Variables personalizadas
      - MOODLE_TOKEN=${MOODLE_TOKEN:-}
      - MOODLE_URL=http://moodle:8080
      - MOODLE_HOST_URL=http://localhost:8080
    ports:
      - "5678:5678"
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - tesis

  mariadb:
    image: bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_DATABASE=moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodle_password
    volumes:
      - mariadb_data:/bitnami/mariadb
    restart: always
    networks:
      - tesis

  moodle:
    image: bitnami/moodle:4.5.4
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_PASSWORD=moodle_password
      - MOODLE_DATABASE_NAME=moodle
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=admin_pass
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_SITE_NAME=MoodleLocal
    ports:
      - "8080:8080"
    volumes:
      - moodle_data:/bitnami/moodle
    depends_on:
      - mariadb
    restart: always
    networks:
      - tesis

  # Servicio Qdrant reemplaza a Weaviate
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always
    networks:
      - tesis

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - tesis

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ollama_webui_data:/app/backend/data
    depends_on:
      - ollama
    ports:
      - "8081:8080"
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://ollama:11434 #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:8081
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    restart: unless-stopped
    networks:
      - tesis

networks:
  tesis:
    driver: bridge
